modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/vinesaucebeep/Simplicity-for-1.18.x/issues"

[[mods]]
modId="simplicity"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}"
displayName="Simplicity"
#updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simplicity"
#logoFile="simplicity.png"
#credits="Thanks for this example mod goes to Java"
authors="vinesaucebeep67"
description='''
Simplicity is a mod that adds in simplistic, vanilla-like features.
'''

[[dependencies.simplicity]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.simplicity]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
